In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 4.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.6/12.6 MB 4.5 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.6 MB 4.0 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.6 MB 3.9 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.6 MB 3.8 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 3.8 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 3.5 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.6 MB 3.2 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.6 MB 3.3 MB/s eta 0:00:03
   --------------------- ------------------ 6.8/12.6 MB 3.4 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 3.4 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 3.4 MB/s eta 0:00:02
   ---

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
import numpy as np

data_1d = np.array([1,2,3,4,5])

In [3]:
print(data_1d.shape)

(5,)


In [12]:
data_2d=np.array([[1,2],[4,5]])
print(data_2d.shape)

(2, 2)


In [13]:
print(data_2d.ndim)

2


In [14]:
print(data_2d)

[[1 2]
 [4 5]]


In [21]:
data_3d = np.array([[[1,2],[5,6],[1,2]],[[1,2],[2,3],[7,8]]])

In [17]:
print(data_3d.ndim)

3


In [22]:
print(data_3d)

[[[1 2]
  [5 6]
  [1 2]]

 [[1 2]
  [2 3]
  [7 8]]]
